version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: crypto_trading_db
    environment:
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: current_password
      POSTGRES_DB: crypto_trading
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trader -d crypto_trading"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    name: crypto_trading_postgres_data 