exchange:
  name: binance
  testnet: false
  api_key: ${BINANCE_API_KEY}
  api_secret: ${BINANCE_API_SECRET}
  base_url: ${BINANCE_API_URL}
  ws_url: ${BINANCE_WS_URL}

trading:
  health_check_interval: ${HEALTH_CHECK_INTERVAL}
  funding_rate_interval: 300        # seconds
  position_interval: 30             # seconds
  signal_interval: 15               # seconds
  monitor_interval: 10              # seconds
  scan_interval: 10                 # seconds
  max_open_trades: ${MAX_OPEN_TRADES}
  min_volume: ${MIN_VOLUME}
  min_liquidity_usdt: 500000
  min_market_cap: ${MIN_MARKET_CAP}
  max_spread: ${MAX_SPREAD}
  min_volatility: ${MIN_VOLATILITY}
  max_volatility: ${MAX_VOLATILITY}
  scalping_mode: false
  risk_per_trade: ${RISK_PER_TRADE}

strategy:
  default_profile: "moderate"
  profiles:
    conservative:
      description: "Low risk, stable returns"
      macd_fast_period: 12
      macd_slow_period: 26
      macd_signal_period: 9
      rsi_overbought: 70
      rsi_oversold: 30
      bb_std_dev: 2.0
      max_position_size: 0.1
      max_leverage: 2.0
      risk_per_trade: 0.01
      max_daily_loss: 0.02
      max_drawdown: 0.05
      volatility_factor: 0.8
      confidence_threshold: 0.8
      
    moderate:
      description: "Balanced risk and returns"
      macd_fast_period: 10
      macd_slow_period: 21
      macd_signal_period: 7
      rsi_overbought: 75
      rsi_oversold: 25
      bb_std_dev: 2.2
      max_position_size: 0.15
      max_leverage: 3.0
      risk_per_trade: 0.015
      max_daily_loss: 0.03
      max_drawdown: 0.08
      volatility_factor: 1.0
      confidence_threshold: 0.7
      
    aggressive:
      description: "Higher risk, higher potential returns"
      macd_fast_period: 8
      macd_slow_period: 17
      macd_signal_period: 5
      rsi_overbought: 80
      rsi_oversold: 20
      bb_std_dev: 2.5
      max_position_size: 0.2
      max_leverage: 5.0
      risk_per_trade: 0.02
      max_daily_loss: 0.04
      max_drawdown: 0.12
      volatility_factor: 1.2
      confidence_threshold: 0.6

risk:
  initial_balance: ${INITIAL_BALANCE:-1000}
  max_daily_loss: ${DAILY_LOSS_LIMIT}
  max_drawdown: ${MAX_DRAWDOWN}
  max_leverage: ${MAX_LEVERAGE}
  position_sizing:
    base_risk: 0.01
    max_risk: 0.05
    confidence_multiplier: 1.5
    volatility_divider: 2.0
  position_size_limit: ${POSITION_SIZE_LIMIT}
  daily_loss_limit: ${DAILY_LOSS_LIMIT}

monitoring:
  funding_rate_check_interval: ${FUNDING_RATE_CHECK_INTERVAL}
  position_update_interval: ${POSITION_UPDATE_INTERVAL}

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/trading_bot.log"

proxy:
  host: ${PROXY_HOST}
  port: ${PROXY_PORT}
  username: ${PROXY_USER}
  password: ${PROXY_PASS}
  proxy_ports: ${PROXY_LIST}
  failover_ports: ${FAILOVER_PORTS}
  symbols: ${TRADING_SYMBOLS} 