exchange:
  name: binance
  api_key: ${BINANCE_API_KEY:-}
  api_secret: ${BINANCE_API_SECRET:-}
  testnet: ${USE_TESTNET:-false}
  base_url: https://fapi.binance.com
  ws_url: wss://fstream.binance.com/ws

trading:
  base_currency: USDT
  max_open_trades: 20
  stake_amount: 500
  stake_currency: USDT
  dry_run: false
  health_check_interval: 60
  position_check_interval: 300
  funding_rate_check_interval: 3600
  risk_per_trade: 0.05

risk:
  max_daily_loss: 5.0
  max_drawdown: 10.0
  max_leverage: 10.0
  position_size_limit: 0.05
  daily_loss_limit: 5.0
  initial_balance: 10000.0

monitoring:
  health_check_interval: 60
  log_level: INFO
  enable_telegram: false
  telegram_token: ${TELEGRAM_TOKEN:-}
  telegram_chat_id: ${TELEGRAM_CHAT_ID:-}
  metrics_enabled: true

paper_trading:
  enabled: true
  initial_balance: 10000.0
  risk_per_trade_pct: 0.05
  max_positions: 20
  leverage: 10.0
  primary_target_dollars: 18.0
  absolute_floor_dollars: 15.0
  stop_loss_dollars: 18.0
  pure_3_rule_mode: true
  mode: pure_profit_scraping
  fees:
    rate: 0.0004  # 0.04% entry fee
    close_rate: 0.0004  # 0.04% exit fee

signal_sources:
  pure_profit_scraping_mode: true
  profit_scraping_primary: true
  allow_opportunity_fallback: false
  allow_flow_trading_fallback: false

proxy:
  USE_PROXY: ${USE_PROXY:-false}
  PROXY_HOST: ${PROXY_HOST:-}
  PROXY_PORT: ${PROXY_PORT:-}
  PROXY_USER: ${PROXY_USER:-}
  PROXY_PASS: ${PROXY_PASS:-}

strategy:
  default_profile: default
  profiles:
    default:
      name: default
      description: Default trading strategy
      parameters:
        entry_threshold: 0.02
        exit_threshold: 0.01
        stop_loss: 0.03
        take_profit: 0.05
        max_position_size: 0.1
        leverage: 10.0
        min_volume: 1000000.0
        min_market_cap: 100000000.0
        max_spread: 0.5
        min_volatility: 0.5
        max_volatility: 5.0
